events {}

http {
    upstream gateway_upstream {
        server gateway:8080;
    }

    upstream frontend_upstream {
        server frontend:4173;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://gateway_upstream/;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://frontend_upstream/;
            try_files $uri /index.html;
        }
    }
}
